### ISSUE TITLE
V16.0 stops functioning on versions before 8.0

### ISSUE THREAD

**Issue by yonib05** [bigcommerce/stencil-cli#489]
v16.0 stops functioning on node versions before 8.0 however according to the BC stencil setup docs on Linux stencil cli is only works from 6.9-7.9

This broke our deployment functionality. We fixed it by specifying v15.9 in our mom install however either bring support to Linux for version 8+ or remove the restriction from executing the commands on the wrong version.

**Comment by bookernath** [comment]
Hey @yonib05, sorry for the disruption.

We've removed support for Node 6 in the most recent version because Node 6 has reached [End of Life](https://github.com/nodejs/Release), and we are obligated to make sure our codebases are on supported versions of runtimes for security reasons.

It's fine to keep using v1.15.9 for now if that works for your workflow, but we'd certainly recommend updating to a Node 8.1 environment in order to make sure you'll continue to get new feature updates, and for the security of your environment.

Our team is working on support for more recent versions of Node and we'll announce when they're available. I'd recommend following the changelog on [developer.bigcommerce.com](https://developer.bigcommerce.com/).

**Comment by yonib05** [comment]
We would love to update node unfortunately we can't get stencil to work with 8.1.0 in Linux .
As you can see.

Our Env:
<img width="845" alt="Screen Shot 2019-07-03 at 10 18 27 AM" src="https://user-images.githubusercontent.com/5503597/60599303-39a30000-9d7c-11e9-9981-2885a9237a26.png">

Logs when we run it:
```bash
npm info lifecycle @bigcommerce/node-sass@3.4.4~install: @bigcommerce/node-sass@3.4.4

> @bigcommerce/node-sass@3.4.4 install /usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/@bigcommerce/node-sass
> node scripts/install.js

module.js:487
    throw err;
    ^

Error: Cannot find module 'combined-stream'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@bigcommerce/stencil-cli/node_modules/form-data/lib/form_data.js:1:84)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
npm info lifecycle @bigcommerce/node-sass@3.4.4~install: Failed to exec install script
npm WARN eslint-config-airbnb@6.2.0 requires a peer of eslint-plugin-react@^4.2.3 but none was installed.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @bigcommerce/node-sass@3.4.4 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @bigcommerce/node-sass@3.4.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-03T14_20_44_344Z-debug.log
Removing intermediate container 848637319cc9
The command '/bin/sh -c npm install -g grunt-cli @bigcommerce/stencil-cli@1.16.0' returned a non-zero code: 1
Action failed: see logs above for details
```
For Full logs see here [https://pastebin.com/ThD769Mt](https://pastebin.com/ThD769Mt)

**Comment by bookernath** [comment]
Thanks, I'll ask the team to take a look at this.

Any difference if you try the latest 8.x? (8.16.0 I believe)

**Comment by karen-white** [comment]
Hey @yonib05 ,
I've run into that issue before and the solution described in this [blog post](https://medium.com/@aguidrevitch/when-installation-of-global-package-using-npm-inside-docker-fails-b551b5dda389) resolved it for me. Can you try running this command as part of your image build?

`npm -g config set user root`

**Comment by yonib05** [comment]
Hey @karen-white,

That worked!! Thank you so much!
on node 8.16.0
```bash
npm -g config set user root
npm install -g @bigcommerce/stencil-cli@1.16
```
